# Generated by Django 5.1.4 on 2024-12-17 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DecimalField(decimal_places=2, max_digits=12)),
                ('velocidade', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
    ]
